# Generated by Django 2.2 on 2019-04-09 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20190408_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checkOut',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
