# Generated by Django 2.2 on 2019-04-09 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20190409_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checkOut',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2019, 4, 9, 6, 29, 17, 998724)),
        ),
    ]
