# Generated by Django 2.2 on 2019-04-09 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20190409_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checkOut',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 7, 25, 45, 150057), null=True),
        ),
    ]
