# Generated by Django 2.2 on 2019-04-09 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_auto_20190409_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='checkOut',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
